---
title: "Rworksheet 6 Final Project"
output:
  html_document:
    df_print: paged
date: "2023-12-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(dplyr)
library(polite)
library(xml2)
library(magrittr)
library(rvest)
library(httr)
library(ggplot2)
library(syuzhet)
library(stringr)
library(tm)
library(wordcloud)
```

```{r airline setting objects}
# Spirit Airline Review

polite::use_manners(save_as = "polite_scrape.R")

airlineURLs <- c(
  'https://www.airlinequality.com/airline-reviews/spirit-airlines/?sortby=post_date%3ADesc&pagesize=100#google_vignette',
  'https://www.airlinequality.com/airline-reviews/spirit-airlines/page/2/?sortby=post_date%3ADesc&pagesize=100',
  'https://www.airlinequality.com/airline-reviews/spirit-airlines/page/3/?sortby=post_date%3ADesc&pagesize=100'
)

allReviewerHeadline <- character()
allUserRating <- character()
allUserReview <- character()

```

```{r airline data scraping}
for (url in airlineURLs) {
  airlineSession <- bow(url, user_agent = "Educational")
  airlineData <- scrape(airlineSession) %>%
    html_elements('div.col-content')
  
  reviewerHeadline <- airlineData %>%
    html_nodes('h2.text_header') %>%
    html_text()
  
  userRating <- airlineData %>%
    html_nodes('div.rating-10') %>%
    html_text()
  
  userReview <- airlineData %>%
    html_nodes('div.text_content') %>%
    html_text()
  
  # Initialize vectors
  reviewerHeadline[is.na(reviewerHeadline)] <- "N/A"
  userRating[is.na(userRating)] <- "N/A"
  userReview[is.na(userReview)] <- "N/A"
  
  # Combine the data from the current URL with the overall data
  allReviewerHeadline <- c(allReviewerHeadline, reviewerHeadline)
  allUserRating <- c(allUserRating, userRating)
  allUserReview <- c(allUserReview, userReview)
}
```

```{r airline_scrape_data_cleaning}
cleanedAllUserReview <- gsub("^(✅ Trip Verified |Not Verified |)\\s*\\|\\s*", "", allUserReview)
cleanedAllUserReview <- gsub("c✅ Trip Verified \\| ", "",  cleanedAllUserReview)
cleanedAllUserReview <- gsub("✅ Trip Verified \\| ", "",  cleanedAllUserReview)

airline_df <- data.frame(
  Review = cleanedAllUserReview
)
cleanedAirlineDF <- distinct(airline_df)
View(cleanedAirlineDF)
```

```{r wordCleaning_writingCSV}
write.csv(airline_df, "airlineDataSet.csv", row.names = FALSE)
cleaned_text <- cleanedAirlineDF$Review
cleaned_text <- gsub("\\|", "", cleaned_text)
cleaned_text <- gsub("\\s+", " ", cleaned_text)
cleaned_text <- gsub("[[:punct:]]", "", cleaned_text)
cleaned_text <- gsub("[[:digit:]]", "", cleaned_text)
cleaned_text <- str_replace_all(cleaned_text, "[^a-zA-Z0-9]", " ")
cleaned_text <- gsub("c✅ Trip Verified \\| ", "",  cleaned_text)
cleaned_text <- gsub("✅ Trip Verified \\| ", "",  cleaned_text)
head(cleaned_text)[1:5]

```


```{r wordcorpus}
wordCorpus <- Corpus(VectorSource(cleaned_text))
wordCorpus <- tm_map(wordCorpus, content_transformer(tolower))
wordCorpus <- tm_map(wordCorpus, removePunctuation)
wordCorpus[[1]]$content
wordCorpus <- tm_map(wordCorpus, removeNumbers)
wordCorpus <- tm_map(wordCorpus, content_transformer(tolower))
wordCorpus[[1]]$content
wordCorpus <- tm_map(wordCorpus, removeWords, stopwords("ENGLISH"))
wordCorpus <- tm_map(wordCorpus, removeWords, stopwords("english"))
wordCorpus <- tm_map(wordCorpus, removeWords, stopwords("SMART"))
wordCorpus[[1]]$content
wordCorpus <- tm_map(wordCorpus, stripWhitespace)
wordCorpus$content[1:10]

wordCorpus <- tm_map(wordCorpus, removeWords, c("usd", "lb", "ft", "fl", "lauderdale", "rep", "ive", "ei", "ktn", "til", "im", "wont", "pm",
                                                "theyre", "st", "nickle", "lbs" , "lax", "ca", "till", "theyll", "youre", "tvs", "id", "jingyao", "li", "stl", "ill",
                                                "sdq", "hr", "yrs", "nk", "hr", "mco", "fll", "didnt", "ubers", "sna", "emailtext", "checkin",
                                                "wasnt", "youll", "couldnt", "noshow", "az", "dr", "checkedcarry", "elses", "isnt", "weve",
                                                "lyft", "customercentric", "lastminute", "careurgency", "bwi", "jetblues", "theyve", "hotelfooduberect",
                                                "iad", "carrion", "costumer"))
wordCorpus <- tm_map(wordCorpus, removeWords, c("la atl","lax","emailtext","tn tx","sna","ceo","tiktok","wifi","tvs","jingyao","stl","lbs","nk","sdq","airbnb","usd","ish","yrs","ga","augusta","fla","hordourves","az","noshow","dfw","hrs","bna","mco","fll","ryanair","tsa","iad","formy","hotelfooduberect","iad","jetblues","jetblue","usa","bwi","vr","fl","fll","careurgency","sonja","expediacom",
                                                "customercentric","airbnb","lyft","companys","empathy ten vuelo para las pm cada minutos nos atrasaban el vuelo al punto las nos cancelan el vuelo para decir nos pueden acomodar el el vuelo de las del peoximo con ni os peque os sufriendo por la espera es la primera vez viajaba con spirit ser la ltima por la voy 
                                                recomendar ni pienso volver utilizarla sirven poca empat","york","nyc","dimeing","checkedcarry", "the", "was", "they", "had", "this", "havethat", "have", "that","and", "our", "are", "with", "but", "for", "their", "which", "this", "were", "will", "then", "would", "just", "when", "this" , "the", "dont", "this"))

wordCorpus <- tm_map(wordCorpus, stripWhitespace)

wordCorpus$content[1:300]
```

```{r wordCloud}
set.seed(1234) # for reproducibility
wordcloud(words = wordCorpus, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35,
          colors=brewer.pal(8, "Dark2"))
```

```{r sentimentAnalysis}
airlineP <- data.frame(text = sapply(wordCorpus, as.character), stringsAsFactors = FALSE)
airlineSentiments <- get_sentiment(airlineP$text,method = "syuzhet")
airlineReviews <- cbind(airlineP, airlineSentiments)
#positive and negative sentiments
encodeSentiment <- function(x) {
  if (x <= -0.5) {
    "1) very negative"
  } else if (x > -0.5 & x < 0) {
    "2) negative"
  } else if (x > 0 & x < 0.5) {
    "4) positive"
  } else if (x >= 0.5) {
    "5) very positive"
  } else {
    "3) neutral"
  }
}


```

```{r plotting}
airlineReviews$airlineSentiments <- sapply(airlineReviews$airlineSentiments,encodeSentiment)

ggplot(airlineReviews, aes(airlineSentiments, fill = airlineSentiments)) +
  geom_bar() +
  theme(legend.position="none", axis.title.x = element_blank()) +
  ylab("Number of tweets") +
  ggtitle("Tweets by Sentiment")
```   